name: Actualizar Facebook

on:
  schedule:
    # Domingo 09:00 hora Bolivia
    - cron: "0 13 * * 0"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar-facebook:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Leer Facebook
        run: python scrape_fb.py

      - name: Guardar publicaciones
        run: |
          git config user.name "Facebook TV Bot"
          git config user.email "actions@github.com"
          git add posts.json
          git diff --cached --quiet || git commit -m "Actualizar publicaciones Facebook"
          git push
